#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
	source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export ANDROID_HOME=/Applications/Android/sdk/platform-tools
if [ -d "$ANDROID_HOME" ] ; then
        export PATH=$PATH:$ANDROID_HOME
fi

# Standard Stuff
if [ -d "$HOME/bin" ] ; then
	export PATH=$PATH:$HOME/bin
fi

# Python 3 Stuff
# Virtualenv/VirtualenvWrapper
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
source /usr/local/bin/virtualenvwrapper.sh

# Go Stuff
if [ -d "$HOME/go" ] ; then
	export GOPATH=$HOME/go
	export PATH=$PATH:$GOPATH/bin
	export GO15VENDOREXPERIMENT=1  
fi

# Super Secret Parameters
alias max="echo 'A god. A true master. Check out his work at http://github.com/mfresonke'"
alias lolz='fortune | tee >(say -v Hysterical) | cowsay -f bong'
