#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
	source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export ANDROID_HOME=/Applications/Android/sdk/platform-tools
if [ -d "$ANDROID_HOME" ] ; then
        export PATH=$PATH:$ANDROID_HOME
fi

# Standard Stuff
if [ -d "$HOME/bin" ] ; then
	export PATH=$PATH:$HOME/bin
fi

# Go Stuff
if [ -d "$HOME/go" ] ; then
	export GOPATH=$HOME/go
	export PATH=$PATH:$GOPATH/bin
	export GO15VENDOREXPERIMENT=1  
fi
