#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
	source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# ======== Remove Unnecessary Additions ========

# Build in diff that's useless (ignoring if it's already unset)
unset -f diff &> /dev/null || true

# Don't Add to History if Space Is Prepended to Command
setopt histignorespace

# Autocomplete on Hidden (dot prefixed) files
setopt globdots

# ======== Source Device-Specific Configs ========

# Check if scutil command exists
if command -v scutil &> /dev/null; then
    # macOS: Use scutil to get LocalHostName
    HOSTNAME=$(scutil --get LocalHostName)
else
    # Other OS: Use hostname command
    HOSTNAME=$(hostname)
fi

# Source Prezto.
export LOCALCFG_FILE="${ZDOTDIR:-$HOME}/.zprezto/local_configs/$HOSTNAME.sh"
if [[ -s "$LOCALCFG_FILE" ]]; then
	source "$LOCALCFG_FILE"
fi

alias localcfg="vim \"$LOCALCFG_FILE\" && echo \"Reloading .zshrc\" && source ~/.zshrc"
alias localcfgcode='code "$LOCALCFG_FILE"'

# ======== PATH Stuff ========

# User Bins
if [ -d "$HOME/bin" ] ; then
	export PATH=$PATH:$HOME/bin
fi

# Go
if [ -d "$HOME/go" ] ; then
	export GOPATH=$HOME/go
	export PATH=$PATH:$GOPATH/bin
fi

# If ANDROID_HOME exists, add the platform tools to the path
if [ -d "$ANDROID_HOME" ] ; then
	export PATH=$PATH:$ANDROID_HOME/platform-tools
fi

# Enable Postgres CLI
if [ -d "/Applications/Postgres.app/Contents/Versions/latest/bin" ] ; then
	export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin"
fi

# fix python (fucking python....)
# eval "$(/opt/homebrew/bin/brew shellenv)"
# export PATH="$(brew --prefix)/opt/python@3/libexec/bin:$PATH"

if type direnv &> /dev/null; then
	eval "$(direnv hook zsh)"
fi

# Super Secret Parameters
alias lolz='fortune | tee >(say) | cowsay -f bong'

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
